mind.icosahedron = {
    'points': {
        "N": { "W": "N", "SW": "N", "SE": "N", "E": "N", "NE": "N", "NW": "N" },
        "A": { "W": "F", "SW": "U", "SE": "Z", "E": "B", "NE": "N", "NW": "N" },
        "B": { "W": "A", "SW": "Z", "SE": "Y", "E": "C", "NE": "N", "NW": "N" },
        "C": { "W": "B", "SW": "Y", "SE": "X", "E": "D", "NE": "N", "NW": "N" },
        "D": { "W": "C", "SW": "X", "SE": "W", "E": "E", "NE": "N", "NW": "N" },
        "E": { "W": "D", "SW": "W", "SE": "V", "E": "F", "NE": "N", "NW": "N" },
        "F": { "W": "E", "SW": "V", "SE": "U", "E": "A", "NE": "N", "NW": "N" },
        "S": { "W": "S", "SW": "S", "SE": "S", "E": "S", "NE": "S", "NW": "S" },
        "U": { "W": "V", "SW": "S", "SE": "S", "E": "Z", "NE": "A", "NW": "F" },
        "V": { "W": "W", "SW": "S", "SE": "S", "E": "U", "NE": "F", "NW": "E" },
        "W": { "W": "X", "SW": "S", "SE": "S", "E": "V", "NE": "E", "NW": "D" },
        "X": { "W": "Y", "SW": "S", "SE": "S", "E": "W", "NE": "D", "NW": "C" },
        "Y": { "W": "Z", "SW": "S", "SE": "S", "E": "X", "NE": "C", "NW": "B" },
        "Z": { "W": "U", "SW": "S", "SE": "S", "E": "Y", "NE": "B", "NW": "A" }
    },
    'spans': {
        "NN": {
            "0": {
                "origin": "N",
                "destination": "N",
                "direction": "W",
                "span_name": "NN"
            },
            "1": { "origin": "N", "destination": "N", "direction": "SW", "span_name": "NN" },
            "2": { "origin": "N", "destination": "N", "direction": "SE", "span_name": "NN" },
            "3": { "origin": "N", "destination": "N", "direction": "E", "span_name": "NN" },
            "4": { "origin": "N", "destination": "N", "direction": "NE", "span_name": "NN" },
            "5": { "origin": "N", "destination": "N", "direction": "NW", "span_name": "NN" }
        },
        "AN": { "0": { "origin": "A", "destination": "N", "direction": "NE", "span_name": "AN" }, "1": { "origin": "A", "destination": "N", "direction": "NW", "span_name": "AN" } },
        "AB": { "0": { "origin": "A", "destination": "B", "direction": "E", "span_name": "AB" }, "1": { "origin": "B", "destination": "A", "direction": "W", "span_name": "AB" } },
        "AF": { "0": { "origin": "A", "destination": "F", "direction": "W", "span_name": "AF" }, "1": { "origin": "F", "destination": "A", "direction": "E", "span_name": "AF" } },
        "AU": { "0": { "origin": "A", "destination": "U", "direction": "SW", "span_name": "AU" }, "1": { "origin": "U", "destination": "A", "direction": "NE", "span_name": "AU" } },
        "AZ": { "0": { "origin": "A", "destination": "Z", "direction": "SE", "span_name": "AZ" }, "1": { "origin": "Z", "destination": "A", "direction": "NW", "span_name": "AZ" } },
        "BN": { "0": { "origin": "B", "destination": "N", "direction": "NE", "span_name": "BN" }, "1": { "origin": "B", "destination": "N", "direction": "NW", "span_name": "BN" } },
        "BC": { "0": { "origin": "B", "destination": "C", "direction": "E", "span_name": "BC" }, "1": { "origin": "C", "destination": "B", "direction": "W", "span_name": "BC" } },
        "BY": { "0": { "origin": "B", "destination": "Y", "direction": "SE", "span_name": "BY" }, "1": { "origin": "Y", "destination": "B", "direction": "NW", "span_name": "BY" } },
        "BZ": { "0": { "origin": "B", "destination": "Z", "direction": "SW", "span_name": "BZ" }, "1": { "origin": "Z", "destination": "B", "direction": "NE", "span_name": "BZ" } },
        "CN": { "0": { "origin": "C", "destination": "N", "direction": "NE", "span_name": "CN" }, "1": { "origin": "C", "destination": "N", "direction": "NW", "span_name": "CN" } },
        "CD": { "0": { "origin": "C", "destination": "D", "direction": "E", "span_name": "CD" }, "1": { "origin": "D", "destination": "C", "direction": "W", "span_name": "CD" } },
        "CX": { "0": { "origin": "C", "destination": "X", "direction": "SE", "span_name": "CX" }, "1": { "origin": "X", "destination": "C", "direction": "NW", "span_name": "CX" } },
        "CY": { "0": { "origin": "C", "destination": "Y", "direction": "SW", "span_name": "CY" }, "1": { "origin": "Y", "destination": "C", "direction": "NE", "span_name": "CY" } },
        "DN": { "0": { "origin": "D", "destination": "N", "direction": "NE", "span_name": "DN" }, "1": { "origin": "D", "destination": "N", "direction": "NW", "span_name": "DN" } },
        "DE": { "0": { "origin": "D", "destination": "E", "direction": "E", "span_name": "DE" }, "1": { "origin": "E", "destination": "D", "direction": "W", "span_name": "DE" } },
        "DW": { "0": { "origin": "D", "destination": "W", "direction": "SE", "span_name": "DW" }, "1": { "origin": "W", "destination": "D", "direction": "NW", "span_name": "DW" } },
        "DX": { "0": { "origin": "D", "destination": "X", "direction": "SW", "span_name": "DX" }, "1": { "origin": "X", "destination": "D", "direction": "NE", "span_name": "DX" } },
        "EN": { "0": { "origin": "E", "destination": "N", "direction": "NE", "span_name": "EN" }, "1": { "origin": "E", "destination": "N", "direction": "NW", "span_name": "EN" } },
        "EF": { "0": { "origin": "E", "destination": "F", "direction": "E", "span_name": "EF" }, "1": { "origin": "F", "destination": "E", "direction": "W", "span_name": "EF" } },
        "EV": { "0": { "origin": "E", "destination": "V", "direction": "SE", "span_name": "EV" }, "1": { "origin": "V", "destination": "E", "direction": "NW", "span_name": "EV" } },
        "EW": { "0": { "origin": "E", "destination": "W", "direction": "SW", "span_name": "EW" }, "1": { "origin": "W", "destination": "E", "direction": "NE", "span_name": "EW" } },
        "FN": { "0": { "origin": "F", "destination": "N", "direction": "NE", "span_name": "FN" }, "1": { "origin": "F", "destination": "N", "direction": "NW", "span_name": "FN" } },
        "FU": { "0": { "origin": "F", "destination": "U", "direction": "SE", "span_name": "FU" }, "1": { "origin": "U", "destination": "F", "direction": "NW", "span_name": "FU" } },
        "FV": { "0": { "origin": "F", "destination": "V", "direction": "SW", "span_name": "FV" }, "1": { "origin": "V", "destination": "F", "direction": "NE", "span_name": "FV" } },
        "SS": { "0": { "origin": "S", "destination": "S", "direction": "W", "span_name": "SS" }, "1": { "origin": "S", "destination": "S", "direction": "SW", "span_name": "SS" }, "2": { "origin": "S", "destination": "S", "direction": "SE", "span_name": "SS" }, "3": { "origin": "S", "destination": "S", "direction": "E", "span_name": "SS" }, "4": { "origin": "S", "destination": "S", "direction": "NE", "span_name": "SS" }, "5": { "origin": "S", "destination": "S", "direction": "NW", "span_name": "SS" } },
        "SU": { "0": { "origin": "U", "destination": "S", "direction": "SW", "span_name": "SU" }, "1": { "origin": "U", "destination": "S", "direction": "SE", "span_name": "SU" } },
        "UV": { "0": { "origin": "U", "destination": "V", "direction": "W", "span_name": "UV" }, "1": { "origin": "V", "destination": "U", "direction": "E", "span_name": "UV" } },
        "UZ": { "0": { "origin": "U", "destination": "Z", "direction": "E", "span_name": "UZ" }, "1": { "origin": "Z", "destination": "U", "direction": "W", "span_name": "UZ" } },
        "SV": { "0": { "origin": "V", "destination": "S", "direction": "SW", "span_name": "SV" }, "1": { "origin": "V", "destination": "S", "direction": "SE", "span_name": "SV" } },
        "VW": { "0": { "origin": "V", "destination": "W", "direction": "W", "span_name": "VW" }, "1": { "origin": "W", "destination": "V", "direction": "E", "span_name": "VW" } },
        "SW": { "0": { "origin": "W", "destination": "S", "direction": "SW", "span_name": "SW" }, "1": { "origin": "W", "destination": "S", "direction": "SE", "span_name": "SW" } },
        "WX": { "0": { "origin": "W", "destination": "X", "direction": "W", "span_name": "WX" }, "1": { "origin": "X", "destination": "W", "direction": "E", "span_name": "WX" } },
        "SX": { "0": { "origin": "X", "destination": "S", "direction": "SW", "span_name": "SX" }, "1": { "origin": "X", "destination": "S", "direction": "SE", "span_name": "SX" } },
        "XY": { "0": { "origin": "X", "destination": "Y", "direction": "W", "span_name": "XY" }, "1": { "origin": "Y", "destination": "X", "direction": "E", "span_name": "XY" } },
        "SY": { "0": { "origin": "Y", "destination": "S", "direction": "SW", "span_name": "SY" }, "1": { "origin": "Y", "destination": "S", "direction": "SE", "span_name": "SY" } },
        "YZ": { "0": { "origin": "Y", "destination": "Z", "direction": "W", "span_name": "YZ" }, "1": { "origin": "Z", "destination": "Y", "direction": "E", "span_name": "YZ" } },
        "SZ": { "0": { "origin": "Z", "destination": "S", "direction": "SW", "span_name": "SZ" }, "1": { "origin": "Z", "destination": "S", "direction": "SE", "span_name": "SZ" } }
    },
    'tiles': {
        "NNN": {
            "0": {
                "origin": "N",
                "first": "N",
                "second": "N",
                "first_span_direction": "W",
                "second_span_direction": "SW",
                "tile_name": "NNN"
            },
            "1": { "origin": "N", "first": "N", "second": "N", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "NNN" },
            "2": { "origin": "N", "first": "N", "second": "N", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "NNN" },
            "3": { "origin": "N", "first": "N", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NNN" },
            "4": { "origin": "N", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NNN" },
            "5": { "origin": "N", "first": "N", "second": "N", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NNN" }
        },
        "NNA": { "0": { "origin": "A", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NNA" } },
        "NFA": { "0": { "origin": "A", "first": "N", "second": "F", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NFA" }, "1": { "origin": "F", "first": "A", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NFA" } },
        "NBA": { "0": { "origin": "A", "first": "B", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NBA" }, "1": { "origin": "B", "first": "N", "second": "A", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NBA" } },
        "UFA": { "0": { "origin": "A", "first": "F", "second": "U", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "UFA" }, "1": { "origin": "F", "first": "U", "second": "A", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "UFA" }, "2": { "origin": "U", "first": "A", "second": "F", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "UFA" } },
        "ZUA": { "0": { "origin": "A", "first": "U", "second": "Z", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "ZUA" }, "1": { "origin": "U", "first": "Z", "second": "A", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "ZUA" }, "2": { "origin": "Z", "first": "A", "second": "U", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "ZUA" } },
        "ZBA": { "0": { "origin": "A", "first": "Z", "second": "B", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "ZBA" }, "1": { "origin": "B", "first": "A", "second": "Z", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "ZBA" }, "2": { "origin": "Z", "first": "B", "second": "A", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "ZBA" } },
        "NNB": { "0": { "origin": "B", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NNB" } },
        "NCB": { "0": { "origin": "B", "first": "C", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NCB" }, "1": { "origin": "C", "first": "N", "second": "B", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NCB" } },
        "YCB": { "0": { "origin": "B", "first": "Y", "second": "C", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "YCB" }, "1": { "origin": "C", "first": "B", "second": "Y", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "YCB" }, "2": { "origin": "Y", "first": "C", "second": "B", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "YCB" } },
        "ZYB": { "0": { "origin": "B", "first": "Z", "second": "Y", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "ZYB" }, "1": { "origin": "Y", "first": "B", "second": "Z", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "ZYB" }, "2": { "origin": "Z", "first": "Y", "second": "B", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "ZYB" } },
        "NNC": { "0": { "origin": "C", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NNC" } },
        "NDC": { "0": { "origin": "C", "first": "D", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NDC" }, "1": { "origin": "D", "first": "N", "second": "C", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NDC" } },
        "XDC": { "0": { "origin": "C", "first": "X", "second": "D", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "XDC" }, "1": { "origin": "D", "first": "C", "second": "X", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "XDC" }, "2": { "origin": "X", "first": "D", "second": "C", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "XDC" } },
        "YXC": { "0": { "origin": "C", "first": "Y", "second": "X", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "YXC" }, "1": { "origin": "X", "first": "C", "second": "Y", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "YXC" }, "2": { "origin": "Y", "first": "X", "second": "C", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "YXC" } },
        "NND": { "0": { "origin": "D", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NND" } },
        "NED": { "0": { "origin": "D", "first": "E", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NED" }, "1": { "origin": "E", "first": "N", "second": "D", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NED" } },
        "WED": { "0": { "origin": "D", "first": "W", "second": "E", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "WED" }, "1": { "origin": "E", "first": "D", "second": "W", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "WED" }, "2": { "origin": "W", "first": "E", "second": "D", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "WED" } },
        "XWD": { "0": { "origin": "D", "first": "X", "second": "W", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "XWD" }, "1": { "origin": "W", "first": "D", "second": "X", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "XWD" }, "2": { "origin": "X", "first": "W", "second": "D", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "XWD" } },
        "NNE": { "0": { "origin": "E", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NNE" } },
        "NFE": { "0": { "origin": "E", "first": "F", "second": "N", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "NFE" }, "1": { "origin": "F", "first": "N", "second": "E", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "NFE" } },
        "VFE": { "0": { "origin": "E", "first": "V", "second": "F", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "VFE" }, "1": { "origin": "F", "first": "E", "second": "V", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "VFE" }, "2": { "origin": "V", "first": "F", "second": "E", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "VFE" } },
        "WVE": { "0": { "origin": "E", "first": "W", "second": "V", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "WVE" }, "1": { "origin": "V", "first": "E", "second": "W", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "WVE" }, "2": { "origin": "W", "first": "V", "second": "E", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "WVE" } },
        "NNF": { "0": { "origin": "F", "first": "N", "second": "N", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "NNF" } },
        "VUF": { "0": { "origin": "F", "first": "V", "second": "U", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "VUF" }, "1": { "origin": "U", "first": "F", "second": "V", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "VUF" }, "2": { "origin": "V", "first": "U", "second": "F", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "VUF" } },
        "SSS": { "0": { "origin": "S", "first": "S", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "SSS" }, "1": { "origin": "S", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "SSS" }, "2": { "origin": "S", "first": "S", "second": "S", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "SSS" }, "3": { "origin": "S", "first": "S", "second": "S", "first_span_direction": "E", "second_span_direction": "NE", "tile_name": "SSS" }, "4": { "origin": "S", "first": "S", "second": "S", "first_span_direction": "NE", "second_span_direction": "NW", "tile_name": "SSS" }, "5": { "origin": "S", "first": "S", "second": "S", "first_span_direction": "NW", "second_span_direction": "W", "tile_name": "SSS" } },
        "USS": { "0": { "origin": "U", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "USS" } },
        "ZUS": { "0": { "origin": "U", "first": "S", "second": "Z", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "ZUS" }, "1": { "origin": "Z", "first": "U", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "ZUS" } },
        "VUS": { "0": { "origin": "U", "first": "V", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "VUS" }, "1": { "origin": "V", "first": "S", "second": "U", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "VUS" } },
        "VSS": { "0": { "origin": "V", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "VSS" } },
        "WVS": { "0": { "origin": "V", "first": "W", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "WVS" }, "1": { "origin": "W", "first": "S", "second": "V", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "WVS" } },
        "WSS": { "0": { "origin": "W", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "WSS" } },
        "XWS": { "0": { "origin": "W", "first": "X", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "XWS" }, "1": { "origin": "X", "first": "S", "second": "W", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "XWS" } },
        "XSS": { "0": { "origin": "X", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "XSS" } },
        "YXS": { "0": { "origin": "X", "first": "Y", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "YXS" }, "1": { "origin": "Y", "first": "S", "second": "X", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "YXS" } },
        "YSS": { "0": { "origin": "Y", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "YSS" } },
        "ZYS": { "0": { "origin": "Y", "first": "Z", "second": "S", "first_span_direction": "W", "second_span_direction": "SW", "tile_name": "ZYS" }, "1": { "origin": "Z", "first": "S", "second": "Y", "first_span_direction": "SE", "second_span_direction": "E", "tile_name": "ZYS" } },
        "ZSS": { "0": { "origin": "Z", "first": "S", "second": "S", "first_span_direction": "SW", "second_span_direction": "SE", "tile_name": "ZSS" } }
    },
}